# Generated by Django 6.0.2 on 2026-02-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_course_credits'),
        ('university', '0002_alter_classroom_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_credits', models.PositiveIntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
