# Generated by Django 6.0.2 on 2026-02-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('building', 'room_number')},
        ),
    ]
